name: bintray-publish

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Change grandlew permissions
      run: chmod +x ./gradlew
      working-directory: client/java
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: client/java
      env:
        FF_WEAK_RANDOM: true
    - name: Publish to Bintray
      run: ./gradlew bintrayUpload
      working-directory: client/java
      env:
        BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}