name: npm-publish

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        working-directory: client/node
      - run: npm run test
        working-directory: client/node

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cd client/node
      - run: npm ci
        working-directory: client/node
      - run: npm run build
        working-directory: client/node
      - run: npm run prepackage
        working-directory: client/node
      - run: npm version 1.0.0-$(date +%Y%m%d%H%M%S)
        working-directory: client/node
      - run: npm publish --access public
        working-directory: client/node
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}