name: pypi-publish

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Pipenv
      run: pip install pipenv --user
      working-directory: client/python
    - name: Install dependencies
      run: python -m pipenv sync --dev
      working-directory: client/python 
    - name: Run tests
      run: python -m pipenv run python -m unittest
      working-directory: client/python
    - name: Sync setup.py dependencies
      run: python -m pipenv run pipenv-setup sync
      working-directory: client/python
    - name: Install pep517
      run: python -m pip install pep517 --user
      working-directory: client/python
    - name: Bump Version
      run: sed -i "s/__VERSION__/1.0.0.a$(date +%Y%m%d%H%M%S)/" pyproject.toml && sed -i "s/__VERSION__/1.0.0.a$(date +%Y%m%d%H%M%S)/" setup.py
      working-directory: client/python
    - name: Build package
      run: python -m pep517.build --source . --out-dir dist/
      working-directory: client/python
    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: client/python/dist